# -*- coding: utf-8 -*-
"""SentimentAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zgpEgDp8yXZHiduZAVUUQJf96BL_LSxf
"""

import pandas as pd
import numpy as np
from textblob import TextBlob
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

from google.colab import files 
files.upload()

df = pd.read_csv('ukraine.csv')
df.index = pd.to_datetime(df.index)
month_index = df.index.to_period('M')
df

#wCreate a function to get the polarity
def getPolarity(text):
  return TextBlob(text).sentiment.polarity

#Create one new column called ‘Polarity
df['Polarity'] = df['TITLE'].apply(getPolarity)

#Show the data set with the new column
df .head(5)

def getSentiment(score):
  if score < 0:
    return 'Negative'
  elif score == 0:
    return 'Neutral'
  else:
    return 'Positive'

#Create a new column to store the sentiment
df['Sentiment'] = df['Polarity'].apply(getSentiment)

df.head(5)

df['Sentiment'].value_counts().plot(kind='bar')
plt.show()